language: go

go:
- 1.10.3

before_install:
- wget "https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-linux-amd64.tar.gz"
- mkdir -p $HOME/bin
- tar -vxz -C $HOME/bin --strip=1 -f glide-0.10.2-linux-amd64.tar.gz
- export PATH="$HOME/bin:$PATH"

install:
- glide install

script:
- diff -u <(echo -n) <(gofmt -d ./)
- go test ./...
